[project]
name = "whosthatpokemon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "langchain-ollama>=0.3.2",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
